### ISSUE TITLE
HUGE number of session rows

### ISSUE THREAD

**Issue by GitHubUserToo** [stefangabos/Zebra_Session#21]
Any reason for a HUGE number of session rows?  I would expect 50,000 - 300,000 maybe, but I have 1,469,143, and the table is 1.1Gb.

I do have expiration set to 60 days, but still, this seems excessive.

I also have slowlog entries like issue # 15 (GET_LOCKs) - if related?

Any suggestions?  Thank you.

**Comment by stefangabos** [comment]
The huge number of session rows can indicate that something's wrong with starting the session and on each subsequent page a new session is created. It can also be because of having a huge number of visitors, visiting your website multiple times a day, each visit creating an entry for 60 days.

As for the slow queries I can only reiterate what I said at #15: it may be because you or your users are authenticated, in the same browser, with the same account, multiple times and doing things that take a lot of time to complete; during this time the row is locked and other sessions (same accounts, different tabs) will be unable to get these locks and will hang.

**Comment by stefangabos** [comment]
This is most likely because of [#16](https://github.com/stefangabos/Zebra_Session/issues/16) and therefore should now be fixed.
