### ISSUE TITLE
String too long

### ISSUE THREAD

**Issue by schmidtl4** [stefangabos/Zebra_Session#52]
I just started getting this error (after upgrading to PHP 8.3.3):
 Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session_data' at row 1 in C:\Apache24\htdocs\bluedots2\vendor\stefangabos\zebra_session\Zebra_Session.php:775 

Zebra was working great for me in 7.4 and the same code that generated the error above, bid not generate an error when I was running PHP 7.4.  

The database column definitions have not changed on my system.

What can be done to fix this?

**Comment by stefangabos** [comment]
I haven't encountered this issue but it looks like something related to a db difference rather than it being related to PHP version difference.

[Here](https://dev.mysql.com/doc/refman/8.0/en/blob.html) it says that this happens when MySQL is in `strict mode` and it may be that on a  previous environment it wasn't. The result in both cases is the same - data longer than the supported size is _written to the db_, the only difference being that a warning is generated in strict mode, while the action is done silently when not in strict mode (and maybe this is why you had no errors previously)

If the data you have is *really* large you can change the `session_data` column type to `MEDIUM BLOB` or `LONG BLOB` depending on the size of the data you are planning to store. 

Also, if you have to store so much data in the session a better solution would be to use `redis` or `memcache` instead of the session

**Comment by joebordes** [comment]
great answer

**Comment by stefangabos** [comment]
In my previous comment I forgot to mention that although data is indeed written to the db, it is truncated to fit the allowed size. I updated my previous comment

**Comment by schmidtl4** [comment]
Great response. Very helpful. Your instinct was spot on. I don't think the amount of session data grew directly as a result of changing PHP versions, though it is likely that the use of session data grew as the code features/functionality continued to expand after the change,   The net result is that changing the `session_data` column to MEDIUM BLOB fixed the issue.  Thank you!
